### PR TITLE
Big optimizations

### PR DESCRIPTION
**Pull request by AnotherJavaCoder**
- Removed the Java NIO imports and only used Java IO
- Removed the depreciated API
- Removed unused fields & methods
- Removed useless method in CommonProxy
- Added French translation
- Added .gitignore from original Forge archive
- Fixed braces and formated sources

### CODE REVIEW

**Comment by TooPointOhh** [comment]
Hey, Arthur. I personally thank you for all your optimizations and fixes made in the project. I will make WORMSTweaker know that you did this.

**Comment by TooPointOhh** [comment]
Hey again, Arthur.
Even though this is an awesome idea, we will be updating the 1.7.10 version before the 1.8 port. If you could make a pull for that, that would be awesome! For now, we will not be accepting this pull!

Warm Regards,
Tyler Ahde

**Comment by AnotherJavaCoder** [comment]
OK, I'll make the optimizations based on the ones I did on this port for the 1.7.10

PS: I know that @WORMSTweaker speak French. Do you too?

**Comment by WORMSTweaker** [comment]
Oui je parle français, mais c'est plus simple pour ceux qui ne le parle pas ^^
So, back to the project now. I will look trought all of the changes, BUT not now.
I'll start to work again on the mod,soon...

**Comment by AnotherJavaCoder** [comment]
Thanks a lot!

**Comment by TooPointOhh** [comment]
lol yes @AnotherJavaCoder I do. I am from Canada and I natively speak English and French. We learn it in school :palm_tree:

**Comment by AnotherJavaCoder** [comment]
Us too in France!

**Pull request closed without merging**
